# Tomcat Java Web App CI/CD Pipeline
trigger:
- main   # Replace with your branch if different

pool:
  name: Default
  demands:
    - agent.name -equals vivek

variables:
  azureSubscription: 'Azuredevops'   # Replace with your authorized service connection name
  webAppName: 'storageapp'           # Your Azure Web App name
  environmentName: 'storageapp'      # Environment in Azure DevOps

stages:
# Stage 1: Build
- stage: Build
  displayName: 'Build Java Web App'
  jobs:
  - job: MavenBuild
    displayName: 'Maven Package and Publish Artifacts'
    pool:
      name: Default
        
    steps:
    - task: Maven@4
      displayName: 'Maven Package'
      inputs:
        mavenPomFile: 'pom.xml'
        mavenOptions: '-Xmx3072m'
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '1.17'
        jdkArchitectureOption: 'x64'
        goals: 'clean package'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'

    - task: CopyFiles@2
      displayName: 'Copy Artifacts to Staging Directory'
      inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)'
        Contents: '**/target/*.war'   # Tomcat apps usually build WAR files
        TargetFolder: '$(Build.ArtifactStagingDirectory)'

    - publish: '$(Build.ArtifactStagingDirectory)'
      artifact: drop

# Stage 2: Deploy
- stage: Deploy
  displayName: 'Deploy Stage'
  dependsOn: Build
  condition: succeeded()
  jobs:
  # Manual approval job
  - job: WaitForApproval
    displayName: 'Manual Approval Before Deployment'
    pool: server
    steps:
    - task: ManualValidation@0
      inputs:
        instructions: 'Please approve before deploying to Azure Tomcat Web App.'
        onTimeout: 'reject'
        timeout: '43200' # 12 hours

  # Deployment job
  - deployment: DeployTomcatWebApp
    displayName: 'Deploy WAR to Azure Tomcat Web App'
    dependsOn: WaitForApproval
    environment: $(environmentName)
    pool:
      name: Default
      
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureWebApp@1
            displayName: 'Deploy to Azure Linux Web App (Tomcat)'
            inputs:
              azureSubscription: '$(azureSubscription)'
              appType: webAppLinux
              appName: '$(webAppName)'
              package: '$(Pipeline.Workspace)/drop/**/*.war'
